export const featureConfigs = {
  'digital-identities': {
    title: 'Digital Identities',
    description: 'Manage AI-powered digital identities with trust scoring',
    itemName: 'Identity',
    detailTitle: 'Digital Identity',
    apiPath: '/digital-identities',
    icon: 'fingerprint',
    color: 'indigo',
    searchFields: ['identity_name', 'identity_type', 'status'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'identity_name', label: 'Name' },
      { key: 'identity_type', label: 'Type', type: 'badge' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'ai_trust_score', label: 'Trust Score', type: 'score' },
      { key: 'created_at', label: 'Created', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'identity_name', label: 'Identity Name' },
      { key: 'identity_type', label: 'Type', type: 'badge' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'user_id', label: 'User ID' },
      { key: 'ai_trust_score', label: 'AI Trust Score', type: 'score' },
      { key: 'public_key', label: 'Public Key', fullWidth: true },
      { key: 'metadata', label: 'Metadata', type: 'json', fullWidth: true },
      { key: 'created_at', label: 'Created', type: 'date' },
      { key: 'updated_at', label: 'Updated', type: 'date' },
    ],
    editFields: [
      { key: 'identity_name', label: 'Identity Name', type: 'text' },
      { key: 'identity_type', label: 'Type', type: 'select', options: ['Personal', 'Organization', 'Government', 'Educational', 'Business', 'Healthcare', 'Financial', 'Travel', 'Device', 'Legal', 'Military', 'Professional', 'Social', 'Academic', 'Emergency'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'pending', 'suspended', 'revoked'] },
      { key: 'public_key', label: 'Public Key', type: 'text' },
      { key: 'metadata', label: 'Metadata (JSON)', type: 'json', default: '{}' },
      { key: 'ai_trust_score', label: 'AI Trust Score', type: 'number' },
    ],
  },

  'did-documents': {
    title: 'DID Documents',
    description: 'Decentralized Identifier documents management',
    itemName: 'DID Document',
    detailTitle: 'DID Document',
    apiPath: '/did-documents',
    icon: 'link',
    color: 'cyan',
    searchFields: ['did_uri', 'method', 'controller', 'status'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'did_uri', label: 'DID URI', type: 'truncate' },
      { key: 'method', label: 'Method' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'created_at', label: 'Created', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'did_uri', label: 'DID URI', fullWidth: true },
      { key: 'method', label: 'Method' },
      { key: 'controller', label: 'Controller' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'verification_methods', label: 'Verification Methods', type: 'json', fullWidth: true },
      { key: 'services', label: 'Services', type: 'json', fullWidth: true },
      { key: 'created_at', label: 'Created', type: 'date' },
    ],
    editFields: [
      { key: 'did_uri', label: 'DID URI', type: 'text' },
      { key: 'method', label: 'Method', type: 'select', options: ['key', 'web', 'ion', 'ethr', 'sov', 'peer', 'pkh', 'tz', 'ebsi', 'cheqd', 'jwk', 'polygonid', 'iota', 'ens', 'gatc'] },
      { key: 'controller', label: 'Controller', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'deactivated'] },
      { key: 'verification_methods', label: 'Verification Methods (JSON)', type: 'json', default: '[]' },
      { key: 'services', label: 'Services (JSON)', type: 'json', default: '[]' },
    ],
  },

  'verifiable-credentials': {
    title: 'Verifiable Credentials',
    description: 'Issue, manage, and verify W3C compliant credentials',
    itemName: 'Credential',
    detailTitle: 'Verifiable Credential',
    apiPath: '/verifiable-credentials',
    icon: 'shield-check',
    color: 'emerald',
    searchFields: ['credential_type', 'issuer', 'subject', 'status'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'credential_type', label: 'Type' },
      { key: 'issuer', label: 'Issuer', type: 'truncate' },
      { key: 'subject', label: 'Subject', type: 'truncate' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'issuance_date', label: 'Issued', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'credential_type', label: 'Credential Type' },
      { key: 'issuer', label: 'Issuer', fullWidth: true },
      { key: 'subject', label: 'Subject', fullWidth: true },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'issuance_date', label: 'Issuance Date', type: 'date' },
      { key: 'expiration_date', label: 'Expiration Date', type: 'date' },
      { key: 'credential_data', label: 'Credential Data', type: 'json', fullWidth: true },
      { key: 'proof', label: 'Proof', type: 'json', fullWidth: true },
    ],
    editFields: [
      { key: 'credential_type', label: 'Credential Type', type: 'text' },
      { key: 'issuer', label: 'Issuer DID', type: 'text' },
      { key: 'subject', label: 'Subject DID', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'revoked', 'expired', 'suspended'] },
      { key: 'credential_data', label: 'Credential Data (JSON)', type: 'json', default: '{}' },
      { key: 'proof', label: 'Proof (JSON)', type: 'json', default: '{}' },
    ],
  },

  'identity-verifications': {
    title: 'Identity Verifications',
    description: 'AI-powered identity verification results',
    itemName: 'Verification',
    detailTitle: 'Identity Verification',
    apiPath: '/identity-verifications',
    icon: 'scan',
    color: 'violet',
    searchFields: ['verification_type', 'verification_method', 'result'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'verification_type', label: 'Type' },
      { key: 'verification_method', label: 'Method' },
      { key: 'result', label: 'Result', type: 'badge' },
      { key: 'confidence_score', label: 'Confidence', type: 'score' },
      { key: 'verified_at', label: 'Verified', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'identity_id', label: 'Identity ID' },
      { key: 'verification_type', label: 'Verification Type' },
      { key: 'verification_method', label: 'Method' },
      { key: 'result', label: 'Result', type: 'badge' },
      { key: 'confidence_score', label: 'Confidence Score', type: 'score' },
      { key: 'details', label: 'Details', type: 'json', fullWidth: true },
      { key: 'verified_at', label: 'Verified At', type: 'date' },
    ],
    editFields: [
      { key: 'identity_id', label: 'Identity ID', type: 'number' },
      { key: 'verification_type', label: 'Type', type: 'select', options: ['Document', 'Biometric', 'Knowledge-Based', 'Email', 'Phone', 'Address', 'Financial', 'Social', 'Device', 'Professional', 'Government', 'Employment', 'Liveness', 'Credential', 'Behavioral'] },
      { key: 'verification_method', label: 'Method', type: 'text' },
      { key: 'result', label: 'Result', type: 'select', options: ['passed', 'failed', 'pending', 'review'] },
      { key: 'confidence_score', label: 'Confidence Score', type: 'number' },
      { key: 'details', label: 'Details (JSON)', type: 'json', default: '{}' },
    ],
  },

  'credential-templates': {
    title: 'Credential Templates',
    description: 'AI-generated and custom credential templates',
    itemName: 'Template',
    detailTitle: 'Credential Template',
    apiPath: '/credential-templates',
    icon: 'layout',
    color: 'pink',
    searchFields: ['template_name', 'template_type', 'status'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'template_name', label: 'Name' },
      { key: 'template_type', label: 'Type' },
      { key: 'ai_generated', label: 'AI Generated', render: (v) => v ? 'Yes' : 'No' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'created_at', label: 'Created', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'template_name', label: 'Template Name' },
      { key: 'template_type', label: 'Type' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'ai_generated', label: 'AI Generated' },
      { key: 'schema_definition', label: 'Schema Definition', type: 'json', fullWidth: true },
      { key: 'visual_design', label: 'Visual Design', type: 'json', fullWidth: true },
      { key: 'issuer_requirements', label: 'Issuer Requirements', type: 'json', fullWidth: true },
    ],
    editFields: [
      { key: 'template_name', label: 'Template Name', type: 'text' },
      { key: 'template_type', label: 'Type', type: 'select', options: ['Education', 'Employment', 'Government', 'Healthcare', 'Professional', 'Financial', 'Travel', 'Certification', 'Insurance', 'Membership', 'Identity', 'Legal', 'Technology', 'Trust'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'draft', 'deprecated'] },
      { key: 'schema_definition', label: 'Schema (JSON)', type: 'json', default: '{"fields": []}' },
      { key: 'visual_design', label: 'Visual Design (JSON)', type: 'json', default: '{}' },
      { key: 'issuer_requirements', label: 'Issuer Requirements (JSON)', type: 'json', default: '{}' },
    ],
  },

  'trust-registry': {
    title: 'Trust Registry',
    description: 'Manage trusted issuers, verifiers, and frameworks',
    itemName: 'Registry Entry',
    detailTitle: 'Trust Registry Entry',
    apiPath: '/trust-registry',
    icon: 'award',
    color: 'amber',
    searchFields: ['entity_name', 'entity_type', 'trust_level', 'governance_framework'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'entity_name', label: 'Entity' },
      { key: 'entity_type', label: 'Type' },
      { key: 'trust_level', label: 'Trust Level', type: 'badge' },
      { key: 'governance_framework', label: 'Framework' },
      { key: 'status', label: 'Status', type: 'badge' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'entity_name', label: 'Entity Name' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'entity_did', label: 'Entity DID', fullWidth: true },
      { key: 'trust_level', label: 'Trust Level', type: 'badge' },
      { key: 'governance_framework', label: 'Governance Framework' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'credentials_types', label: 'Credential Types', type: 'json', fullWidth: true },
      { key: 'verified_at', label: 'Verified At', type: 'date' },
    ],
    editFields: [
      { key: 'entity_name', label: 'Entity Name', type: 'text' },
      { key: 'entity_type', label: 'Entity Type', type: 'select', options: ['Government Issuer', 'Educational Issuer', 'Corporate Issuer', 'Financial Issuer', 'Healthcare Issuer', 'Verifier', 'Trust Framework', 'Professional Body', 'Certification Issuer', 'Municipal Issuer', 'Standards Body', 'Supranational Issuer'] },
      { key: 'entity_did', label: 'Entity DID', type: 'text' },
      { key: 'trust_level', label: 'Trust Level', type: 'select', options: ['sovereign', 'high', 'medium', 'low'] },
      { key: 'governance_framework', label: 'Governance Framework', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'suspended', 'revoked'] },
      { key: 'credentials_types', label: 'Credential Types (JSON)', type: 'json', default: '[]' },
    ],
  },

  'credential-schemas': {
    title: 'Credential Schemas',
    description: 'Define and manage credential data schemas',
    itemName: 'Schema',
    detailTitle: 'Credential Schema',
    apiPath: '/credential-schemas',
    icon: 'database',
    color: 'teal',
    searchFields: ['schema_name', 'schema_type', 'schema_version'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'schema_name', label: 'Name' },
      { key: 'schema_version', label: 'Version' },
      { key: 'schema_type', label: 'Type' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'created_at', label: 'Created', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'schema_name', label: 'Schema Name' },
      { key: 'schema_version', label: 'Version' },
      { key: 'schema_type', label: 'Type' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'properties', label: 'Properties', type: 'json', fullWidth: true },
      { key: 'required_fields', label: 'Required Fields', type: 'json', fullWidth: true },
    ],
    editFields: [
      { key: 'schema_name', label: 'Schema Name', type: 'text' },
      { key: 'schema_version', label: 'Version', type: 'text' },
      { key: 'schema_type', label: 'Type', type: 'select', options: ['Identity', 'Education', 'Employment', 'Healthcare', 'Financial', 'Government', 'Professional', 'Organization', 'Technology', 'Travel', 'Insurance', 'Certification'] },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'draft', 'deprecated'] },
      { key: 'properties', label: 'Properties (JSON)', type: 'json', default: '{}' },
      { key: 'required_fields', label: 'Required Fields (JSON)', type: 'json', default: '[]' },
    ],
  },

  'revocation-entries': {
    title: 'Revocation Registry',
    description: 'Track and manage credential revocations',
    itemName: 'Revocation',
    detailTitle: 'Revocation Entry',
    apiPath: '/revocation-entries',
    icon: 'x-circle',
    color: 'red',
    searchFields: ['reason', 'revoked_by'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'credential_id', label: 'Credential ID' },
      { key: 'reason', label: 'Reason' },
      { key: 'revoked_by', label: 'Revoked By', type: 'truncate' },
      { key: 'revoked_at', label: 'Revoked At', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'credential_id', label: 'Credential ID' },
      { key: 'reason', label: 'Reason', fullWidth: true },
      { key: 'revoked_by', label: 'Revoked By', fullWidth: true },
      { key: 'revocation_list_url', label: 'Revocation List URL', fullWidth: true },
      { key: 'revoked_at', label: 'Revoked At', type: 'date' },
    ],
    editFields: [
      { key: 'credential_id', label: 'Credential ID', type: 'number' },
      { key: 'reason', label: 'Reason', type: 'textarea' },
      { key: 'revoked_by', label: 'Revoked By', type: 'text' },
      { key: 'revocation_list_url', label: 'Revocation List URL', type: 'text' },
    ],
  },

  'risk-assessments': {
    title: 'Risk Assessments',
    description: 'AI-powered identity and credential risk scoring',
    itemName: 'Assessment',
    detailTitle: 'Risk Assessment',
    apiPath: '/risk-assessments',
    icon: 'alert-triangle',
    color: 'orange',
    searchFields: ['entity_type', 'risk_level'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'risk_level', label: 'Risk Level', type: 'badge' },
      { key: 'risk_score', label: 'Risk Score', type: 'score' },
      { key: 'assessed_at', label: 'Assessed', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'risk_level', label: 'Risk Level', type: 'badge' },
      { key: 'risk_score', label: 'Risk Score', type: 'score' },
      { key: 'risk_factors', label: 'Risk Factors', type: 'json', fullWidth: true },
      { key: 'recommendations', label: 'Recommendations', type: 'json', fullWidth: true },
      { key: 'assessed_at', label: 'Assessed At', type: 'date' },
    ],
    editFields: [
      { key: 'entity_type', label: 'Entity Type', type: 'select', options: ['identity', 'credential', 'did', 'presentation'] },
      { key: 'entity_id', label: 'Entity ID', type: 'number' },
      { key: 'risk_level', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'risk_score', label: 'Risk Score (0-100)', type: 'number' },
      { key: 'risk_factors', label: 'Risk Factors (JSON)', type: 'json', default: '[]' },
      { key: 'recommendations', label: 'Recommendations (JSON)', type: 'json', default: '[]' },
    ],
  },

  'compliance-checks': {
    title: 'Compliance Checks',
    description: 'Framework compliance verification and reporting',
    itemName: 'Compliance Check',
    detailTitle: 'Compliance Check',
    apiPath: '/compliance-checks',
    icon: 'clipboard-check',
    color: 'lime',
    searchFields: ['check_name', 'framework', 'status'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'check_name', label: 'Check Name' },
      { key: 'framework', label: 'Framework' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'checked_at', label: 'Checked', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'check_name', label: 'Check Name', fullWidth: true },
      { key: 'framework', label: 'Framework' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'findings', label: 'Findings', type: 'json', fullWidth: true },
      { key: 'checked_at', label: 'Checked At', type: 'date' },
    ],
    editFields: [
      { key: 'check_name', label: 'Check Name', type: 'text' },
      { key: 'framework', label: 'Framework', type: 'select', options: ['GDPR', 'eIDAS', 'HIPAA', 'SOC2', 'PCI-DSS', 'NIST-800-63', 'ISO-27001', 'W3C-VC', 'CCPA', 'KYC-AML', 'FIDO2', 'DIF-PE', 'OIDC', 'ToIP', 'Basel-III'] },
      { key: 'entity_type', label: 'Entity Type', type: 'select', options: ['identity', 'credential', 'did'] },
      { key: 'entity_id', label: 'Entity ID', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['passed', 'failed', 'warning', 'pending'] },
      { key: 'findings', label: 'Findings (JSON)', type: 'json', default: '[]' },
    ],
  },

  'fraud-alerts': {
    title: 'Fraud Alerts',
    description: 'AI-powered fraud detection and alerting',
    itemName: 'Alert',
    detailTitle: 'Fraud Alert',
    apiPath: '/fraud-alerts',
    icon: 'alert-octagon',
    color: 'rose',
    searchFields: ['alert_type', 'severity', 'description', 'status'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'alert_type', label: 'Alert Type' },
      { key: 'severity', label: 'Severity', type: 'badge' },
      { key: 'entity_type', label: 'Entity' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'created_at', label: 'Created', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'alert_type', label: 'Alert Type' },
      { key: 'severity', label: 'Severity', type: 'badge' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'description', label: 'Description', fullWidth: true },
      { key: 'indicators', label: 'Indicators', type: 'json', fullWidth: true },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'resolved_at', label: 'Resolved At', type: 'date' },
      { key: 'created_at', label: 'Created At', type: 'date' },
    ],
    editFields: [
      { key: 'alert_type', label: 'Alert Type', type: 'select', options: ['Identity Theft', 'Credential Forgery', 'Phishing Attack', 'Replay Attack', 'Synthetic Identity', 'Credential Stuffing', 'DID Hijacking', 'Insider Threat', 'Man-in-the-Middle', 'Account Takeover', 'Deepfake Detection', 'Sybil Attack', 'Credential Harvesting', 'Key Compromise', 'Presentation Manipulation'] },
      { key: 'severity', label: 'Severity', type: 'select', options: ['critical', 'high', 'medium', 'low'] },
      { key: 'entity_type', label: 'Entity Type', type: 'select', options: ['identity', 'credential', 'did', 'presentation'] },
      { key: 'entity_id', label: 'Entity ID', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'indicators', label: 'Indicators (JSON)', type: 'json', default: '[]' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'investigating', 'resolved', 'false_positive'] },
    ],
  },

  'credential-shares': {
    title: 'Credential Sharing',
    description: 'Selective disclosure and credential sharing management',
    itemName: 'Share',
    detailTitle: 'Credential Share',
    apiPath: '/credential-shares',
    icon: 'share-2',
    color: 'sky',
    searchFields: ['shared_with', 'purpose', 'status'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'credential_id', label: 'Credential' },
      { key: 'shared_with', label: 'Shared With', type: 'truncate' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'expires_at', label: 'Expires', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'credential_id', label: 'Credential ID' },
      { key: 'shared_with', label: 'Shared With', fullWidth: true },
      { key: 'purpose', label: 'Purpose' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'disclosed_fields', label: 'Disclosed Fields', type: 'json', fullWidth: true },
      { key: 'access_policy', label: 'Access Policy', type: 'json', fullWidth: true },
      { key: 'shared_at', label: 'Shared At', type: 'date' },
      { key: 'expires_at', label: 'Expires At', type: 'date' },
    ],
    editFields: [
      { key: 'credential_id', label: 'Credential ID', type: 'number' },
      { key: 'shared_with', label: 'Shared With (DID)', type: 'text' },
      { key: 'purpose', label: 'Purpose', type: 'text' },
      { key: 'disclosed_fields', label: 'Disclosed Fields (JSON)', type: 'json', default: '[]' },
      { key: 'access_policy', label: 'Access Policy (JSON)', type: 'json', default: '{}' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'expired', 'revoked'] },
    ],
  },

  'presentation-requests': {
    title: 'Presentation Requests',
    description: 'Manage verifiable presentation exchanges',
    itemName: 'Request',
    detailTitle: 'Presentation Request',
    apiPath: '/presentation-requests',
    icon: 'send',
    color: 'fuchsia',
    searchFields: ['verifier', 'purpose', 'status'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'verifier', label: 'Verifier' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'created_at', label: 'Created', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'verifier', label: 'Verifier' },
      { key: 'purpose', label: 'Purpose' },
      { key: 'status', label: 'Status', type: 'badge' },
      { key: 'requested_credentials', label: 'Requested Credentials', type: 'json', fullWidth: true },
      { key: 'constraints', label: 'Constraints', type: 'json', fullWidth: true },
      { key: 'responded_at', label: 'Responded At', type: 'date' },
      { key: 'created_at', label: 'Created At', type: 'date' },
    ],
    editFields: [
      { key: 'verifier', label: 'Verifier', type: 'text' },
      { key: 'purpose', label: 'Purpose', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'fulfilled', 'expired', 'rejected'] },
      { key: 'requested_credentials', label: 'Requested Credentials (JSON)', type: 'json', default: '[]' },
      { key: 'constraints', label: 'Constraints (JSON)', type: 'json', default: '{}' },
    ],
  },

  'audit-logs': {
    title: 'Audit Trail',
    description: 'Complete audit trail with AI anomaly detection',
    itemName: 'Log Entry',
    detailTitle: 'Audit Log Entry',
    apiPath: '/audit-logs',
    icon: 'file-text',
    color: 'slate',
    searchFields: ['action', 'entity_type', 'actor'],
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'action', label: 'Action' },
      { key: 'entity_type', label: 'Entity' },
      { key: 'actor', label: 'Actor', type: 'truncate' },
      { key: 'ai_anomaly_flag', label: 'Anomaly', render: (v) => v ? 'Yes' : 'No' },
      { key: 'created_at', label: 'Time', type: 'date' },
    ],
    displayFields: [
      { key: 'id', label: 'ID' },
      { key: 'action', label: 'Action' },
      { key: 'entity_type', label: 'Entity Type' },
      { key: 'entity_id', label: 'Entity ID' },
      { key: 'actor', label: 'Actor', fullWidth: true },
      { key: 'details', label: 'Details', type: 'json', fullWidth: true },
      { key: 'ip_address', label: 'IP Address' },
      { key: 'ai_anomaly_flag', label: 'AI Anomaly Flag' },
      { key: 'created_at', label: 'Created At', type: 'date' },
    ],
    editFields: [
      { key: 'action', label: 'Action', type: 'text' },
      { key: 'entity_type', label: 'Entity Type', type: 'text' },
      { key: 'entity_id', label: 'Entity ID', type: 'number' },
      { key: 'actor', label: 'Actor', type: 'text' },
      { key: 'details', label: 'Details (JSON)', type: 'json', default: '{}' },
      { key: 'ip_address', label: 'IP Address', type: 'text' },
    ],
  },
};
